---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - results.stackrox.io
  resources:
  - resultsexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - results.stackrox.io
  resources:
  - resultsexporters/finalizers
  verbs:
  - update
- apiGroups:
  - results.stackrox.io
  resources:
  - resultsexporters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.stackrox.io
  resources:
  - alerts
  - clusteralerts
  - clustersecurityresults
  - imagevulnerabilities
  - nodevulnerabilities
  - securityresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.stackrox.io
  resources:
  - alerts/status
  - clusteralerts/status
  - clustersecurityresults/status
  - imagevulnerabilities/status
  - nodevulnerabilities/status
  - securityresults/status
  verbs:
  - get
  - patch
  - update
