## Append samples of your project ##
resources:
- results_v1alpha1_resultsexporter.yaml
- security_v1alpha1_alert.yaml
- security_v1alpha1_imagevulnerability.yaml
- security_v1alpha1_nodevulnerability.yaml
- security_v1alpha1_securityresults.yaml
- security_v1alpha1_clustersecurityresults.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
