apiVersion: security.stackrox.io/v1alpha1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: stackrox-results-operator
    app.kubernetes.io/managed-by: kustomize
  name: alert-sample
spec:
  # TODO(user): Add fields here
