apiVersion: results.stackrox.io/v1alpha1
kind: SecurityResults
metadata:
  labels:
    app.kubernetes.io/name: stackrox-results-operator
    app.kubernetes.io/managed-by: kustomize
  name: securityresults-sample
spec:
  # TODO(user): Add fields here
